repos:
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
      language_version: python3

- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v1.4.0
  hooks:
   - id: end-of-file-fixer
     exclude: .bumpversion.cfg
   - id: trailing-whitespace
     exclude: .bumpversion.cfg
   - id: check-case-conflict
   - id: check-merge-conflict
   - id: check-yaml
     args: ['--unsafe']
   - id: detect-private-key
   - id: forbid-new-submodules
   - id: no-commit-to-branch
     args: ['--branch', 'main']
   - id: check-json
   - id: pretty-format-json
   - id: check-added-large-files
   - id: debug-statements
   - id: flake8

- repo: https://github.com/vikalpj/pre-commit-python-sorter
  sha: 5294cde9d51cff119af537e987c30c320e9fbe2f
  hooks:
   - id: python-import-sorter
